=== Wonderwice/L1-Web/XML/movie.dtd
<!ENTITY % id "id      ID    #IMPLIED">
<!ENTITY % year "2008|2010|2011|2012">
<!ENTITY % duree "112min|114min|124min|125min|126min|143min">
<!ENTITY % pist_num "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27">
<!ENTITY % note "1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|100">
<!ENTITY % personality
        "%id;
         prenom  CDATA #REQUIRED
         nom     CDATA #REQUIRED">

<!ELEMENT movie (fiche_technique, synopsis, bande_originale, note?, box_office, distinctions*, photo+)>
<!ATTLIST movie
          %id;
          annee_sortie %year;  #REQUIRED
          durée        %duree; #REQUIRED>

<!ELEMENT fiche_technique (producteur+, budget, realisateur, scenariste+, main_actors, société_prod+)>
<!ATTLIST fiche_technique
          %id;>

<!ELEMENT producteur EMPTY>
<!ATTLIST producteur
          %personality;>

<!ELEMENT budget (#PCDATA)>
<!ATTLIST budget
          %id;>

<!ELEMENT realisateur EMPTY>
<!ATTLIST realisateur
          %personality;>

<!ELEMENT scenariste EMPTY>
<!ATTLIST scenariste
          %personality;>

<!ELEMENT main_actors (actor+)>
<!ATTLIST main_actors
          %id;>

<!ELEMENT actor EMPTY>
<!ATTLIST actor
          %personality;>

<!ELEMENT société_prod (#PCDATA)>
<!ATTLIST société_prod
          %id;>

<!ELEMENT synopsis (#PCDATA)>
<!ATTLIST synopsis
          %id;>

<!ELEMENT bande_originale (son+)>
<!ATTLIST bande_originale
          %id;>

<!ELEMENT son EMPTY>
<!ATTLIST son
          %id;
          numero  %pist_num; #REQUIRED
          titre   CDATA      #REQUIRED
          longeur CDATA      #REQUIRED>

<!ELEMENT note %note;>
<!ATTLIST note
          %id;>

<!ELEMENT box_office (#PCDATA)>
<!ATTLIST box_office
          %id;>


<!ELEMENT distinctions (nomination*, recompense*)>
<!ATTLIST distinctions
          %id;>

<!ELEMENT nomination (#PCDATA)>
<!ATTLIST nomination
          %id;
          type  CDATA #REQUIRED>

<!ELEMENT recompense (#PCDATA)>
<!ATTLIST recompense
          %id;
          type  CDATA  #REQUIRED>

<!ELEMENT photo EMPTY>
<!ATTLIST photo
          %id;
          src   CDATA #REQUIRED
          alt   CDATA #REQUIRED>

=== Wonderwice/L1-Web/XML/iron_man.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur Alexei Czornyj -->
<!DOCTYPE movie SYSTEM "movie.dtd">
<movie annee_sortie="2010" durée="126min">
    <fiche_technique>
        <producteur prenom="Avi" nom="Arad"/>
        <producteur prenom="Kevin" nom="Feige"/>
        <budget>140 000 000 $</budget>
        <realisateur prenom="Jon" nom="Favreau"/>
        <scenariste prenom="Matt" nom="Holloway"/>
        <scenariste prenom="Art" nom="Marcum"/>
        <scenariste prenom="Mark" nom="Fergus"/>
        <scenariste prenom="Hawk" nom="Ostby"/>
        <scenariste prenom="John" nom="August"/>
        <main_actors>
            <actor prenom="Robert" nom="Downey Jr."/>
            <actor prenom="Gwyneth" nom="Paltrow"/>
            <actor prenom="Terrence" nom="Howard"/>
            <actor prenom="Jeff" nom="Bridges"/>
        </main_actors>
        <société_prod>Marvel Studios</société_prod>
        <société_prod>Fairview Entertainment</société_prod>
    </fiche_technique>
    <synopsis>Tony Stark est un industriel milliardaire et un inventeur de génie qui est kidnappé et forcé de construire
        une arme dévastatrice.
        Au lieu de cela, utilisant son intelligence et son ingéniosité, Tony construit une armure de haute technologie
        et échappe à la captivité.
        Lorsqu'il découvre un complot néfaste aux implications mondiales, il enfile sa puissante armure et jure de
        protéger le monde en tant qu'Iron Man.
    </synopsis>
    <bande_originale>
        <son numero="1" titre="Driving With The Top Down" longeur="3:10"/>
        <son numero="2" titre="Iron Man (2008 version) (John O'Brien and Rick Boston)" longeur="1:05"/>
        <son numero="3" titre="Merchant of Death" longeur="2:00"/>
        <son numero="4" titre="Trinkets to Kill a Prince" longeur="3:08"/>
        <son numero="5" titre="Mark I" longeur="3:54"/>
        <son numero="6" titre="Fireman" longeur="2:09"/>
        <son numero="7" titre="Vacation's Over" longeur="3:35"/>
        <son numero="8" titre="Golden Egg" longeur="4:13"/>
        <son numero="9" titre="Damn Kid (DJ Boborobo)" longeur="1:13"/>
        <son numero="10" titre="Mark II" longeur="2:49"/>
        <son numero="11" titre="Extra Dry, Extra Olives" longeur="1:44"/>
        <son numero="12" titre="Iron Man" longeur="3:33"/>
        <son numero="13" titre="Gulmira" longeur="4:06"/>
        <son numero="14" titre="Are Those Bullet Holes ?" longeur="2:00"/>
        <son numero="15" titre="Section 16" longeur="2:34"/>
        <son numero="16" titre="Iron Monger" longeur="4:45"/>
        <son numero="17" titre="Arc Reactor" longeur="3:56"/>
        <son numero="18" titre="Institutionalized (Suicidal Tendencies)" longeur="3:49"/>
        <son numero="19" titre="Iron Man" longeur="0:21"/>
    </bande_originale>
    <note>74</note>
    <box_office>585 366 247 $</box_office>
    <distinctions>
        <nomination type="Teen Choice Awards 2008">Meilleur acteur dans un film d'action/aventure pour Robert Downey
            Jr.
        </nomination>
        <nomination type="Teen Choice Awards 2008">Meilleure actrice dans un film d'action/aventure pour Gwyneth
            Paltrow
        </nomination>
        <nomination type="Teen Choice Awards 2008">Meilleur méchant au cinéma pour Jeff Bridges</nomination>
        <nomination type="MTV Movie Awards 2009">Meilleur film</nomination>
        <nomination type="MTV Movie Awards 2009">Meilleur acteur pour Robert Downey Jr.</nomination>
    </distinctions>
    <photo src="iron_man.png" alt="Iron Man"/>
</movie>

=== Wonderwice/L1-Web/XML/thor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auteur Styven Drui -->
<!DOCTYPE movie SYSTEM "movie.dtd">
<movie annee_sortie="2011" durée="114min">
    <fiche_technique>
        <producteur prenom="Stan" nom="Lee"/>
        <producteur prenom="Kevin" nom="Feige"/>
        <producteur prenom="Jaimie" nom="Alexander"/>
        <producteur prenom="Victoria" nom="Alonso"/>
        <producteur prenom="Craig" nom="Kyle"/>
        <budget>150 000 000 $</budget>
        <realisateur prenom="Kenneth" nom="Branagh"/>
        <scenariste prenom="Ashley" nom="Miller"/>
        <scenariste prenom="Zack" nom="Stentz"/>
        <scenariste prenom="Don" nom="Payne"/>
        <main_actors>
            <actor prenom="Chris" nom="Hemsworth"/>
            <actor prenom="Natalie" nom="Portman"/>
            <actor prenom="Tom" nom="Hiddleston"/>
            <actor prenom="Anthony" nom="Hopkins"/>
        </main_actors>
        <société_prod>Marvel Studios</société_prod>
    </fiche_technique>
    <synopsis>Le roi Odin règne avec sagesse sur son royaume. Une entente maintient la paix avec les Géants du monde
        glacé de Jotunheim.
        Les gestes irréfléchis du jeune Thor, pressenti pour prendre la place de son père sur le trône,
        mettent cependant en péril la paix fragile entre les deux peuples, ce qui pousse son père à le bannir sur Terre.
        Dépouillé de ses pouvoirs, Thor doit apprendre la véritable valeur d'un roi. Pendant ce temps,
        le demi-frère de Thor essaie de prendre possession du trône.
    </synopsis>
    <bande_originale>
        <son numero="1" titre="Chasing the Storm" longeur="3:11"/>
        <son numero="2" titre="Prologue" longeur="3:09"/>
        <son numero="3" titre="Sons of Odin" longeur="1:48"/>
        <son numero="4" titre="A New King" longeur="3:00"/>
        <son numero="5" titre="Ride to Observatory" longeur="2:10"/>
        <son numero="6" titre="To Jotunheim" longeur="2:19"/>
        <son numero="7" titre="Laufey" longeur="3:40"/>
        <son numero="8" titre="Frost Giant Battle" longeur="4:22"/>
        <son numero="9" titre="Banishment" longeur="1:53"/>
        <son numero="10" titre="Crisis In Asgard" longeur="2:18"/>
        <son numero="11" titre="Odin Confesses" longeur="2:43"/>
        <son numero="12" titre="Hammer Found" longeur="1:11"/>
        <son numero="13" titre="Urgent Matter" longeur="2:21"/>
        <son numero="14" titre="The Compound" longeur="7:40"/>
        <son numero="15" titre="Loki’s Lie" longeur="1:54"/>
        <son numero="16" titre="My Bastard Son" longeur="2:39"/>
        <son numero="17" titre="Science and Magic" longeur="2:53"/>
        <son numero="18" titre="The Destroyer" longeur="2:57"/>
        <son numero="19" titre="Forgive Me" longeur="2:40"/>
        <son numero="20" titre="Thor Kills the Destroyer" longeur="1:53"/>
        <son numero="21" titre="Brothers Fight" longeur="6:59"/>
        <son numero="22" titre="Letting Go" longeur="3:17"/>
        <son numero="23" titre="Can You See Jane?" longeur="2:23"/>
        <son numero="24" titre="Earth to Asgard" longeur="2:33"/>
    </bande_originale>
    <note>57</note>
    <box_office>449 326 618 $</box_office>
    <distinctions>
        <nomination type="Teen Choice Awards 2011">révélation masculine de l'année pour Chris Hemsworth</nomination>
        <nomination type="MTV Movie Awards 2012">meilleur héros pour Chris Hemsworth</nomination>
    </distinctions>
    <photo src="thor-image.jpg" alt="Thor"/>
</movie>

=== Wonderwice/L1-Web/XML/hulk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movie SYSTEM "movie.dtd">
<movie annee_sortie="2008" durée="112min">
    <fiche_technique>
        <producteur prenom="Avi" nom="Arad"/>
        <producteur prenom="Kevin" nom="Feige"/>
        <producteur prenom="Gale" nom="Anne Hurd"/>
        <budget>150 000 000 $</budget>
        <realisateur prenom="Louis" nom="Leterrier"/>
        <scenariste prenom="Zak" nom="Penn"/>
        <scenariste prenom="Edward" nom="Norton"/>
        <scenariste prenom="Louis" nom="Letterier"/>
        <main_actors>
            <actor prenom="Edward" nom="Norton"/>
            <actor prenom="Liv" nom="Tyler"/>
            <actor prenom="Tim" nom="Roth"/>
            <actor prenom="William" nom="Hurt"/>
        </main_actors>
        <société_prod>Marvel Studios</société_prod>
        <société_prod>Valhalla Motion Pictures</société_prod>
    </fiche_technique>
    <synopsis>Le scientifique Bruce Banner cherche désespérément un antidote aux radiations gamma qui ont créé Hulk.
        Il vit dans l'ombre, toujours amoureux de la belle Betty Ross et parcourt la planète à la recherche d'un remède.
        La force destructrice de Hulk attire le Général Thunderbolt Ross et son bras droit Blonsky qui rêvent de
        l'utiliser à des fins militaires. Ils tentent de développer un sérum pour créer des soldats surpuissants.
        De retour aux Etats-Unis, Bruce Banner se découvre un nouvel ennemi. Après avoir essayé le sérum expérimental,
        Blonsky est devenu L'Abomination, un monstre incontrôlable dont la force pure est même supérieure à celle de Hulk.
        Devenu fou, il s'est transformé en plein coeur de New York.
        Pour sauver la ville de la destruction totale, Bruce Banner va devoir faire appel au monstre qui sommeille en lui...</synopsis>
    <bande_originale>
        <son numero="1" titre="The Arctic" longeur="2:47"/>
        <son numero="2" titre="Main Title" longeur="2:39"/>
        <son numero="3" titre="Rocinha Favela" longeur="3:11"/>
        <son numero="4" titre="A Drop of Blood" longeur="1:35"/>
        <son numero="5" titre="The Flower" longeur="2:49"/>
        <son numero="6" titre="Ross' Team" longeur="1:33"/>
        <son numero="7" titre="Mr. Blue" longeur="1:03"/>
        <son numero="8" titre="Favela Escape" longeur="3:35"/>
        <son numero="9" titre="It Was Banner" longeur="1:32"/>
        <son numero="10" titre="That Is the Target" longeur="5:34"/>
        <son numero="11" titre="Bruce Goes Home" longeur="1:25"/>
        <son numero="12" titre="Ross and Blonsky" longeur="3:15"/>
        <son numero="13" titre="Return to Culver University" longeur="2:39"/>
        <son numero="14" titre="The Lab" longeur="1:17"/>
        <son numero="15" titre="Reunion" longeur="3:37"/>
        <son numero="16" titre="The Data/The Vial" longeur="1:20"/>
        <son numero="17" titre="They're Here" longeur="3:07"/>
        <son numero="18" titre="Give Him Everything You've Got" longeur="6:08"/>
        <son numero="19" titre="Bruce Can't Stay" longeur="1:54"/>
        <son numero="20" titre="First Injection" longeur="1:03"/>
        <son numero="21" titre="Is It Safe?" longeur="1:07"/>
        <son numero="22" titre="Hulk Theme" longeur="3:59"/>
    </bande_originale>
    <note>61</note>
    <box_office>264 770 996 $</box_office>
    <photo src="hulk.jpg" alt="Hulk"/>
</movie>
